services:
  - type: web
    name: honey-backend
    runtime: python
    rootDir: backend/honey
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate && daphne -b 0.0.0.0 -p $PORT config.asgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: honey-db
          property: connectionString
      - key: FRONTEND_URL
        value: "https://honey-frontend.onrender.com"
    healthCheckPath: /swagger/

databases:
  - name: honey-db
    databaseName: honeydb
    plan: free
